export const personList = [
    {
        pid: 1,
        fullname: "charlo",
        idnumber: "10-10525",
        applicant: "Employee",
        position: "Janitor",
        courseandyear: "",
        address: "dopaj, dupax del sur, nueva vizcaya",
        mobilenumber: "09677160884",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2028-08-24",
        vehiclewheels: "4-Wheeled",
        platenumber: "AKA 1023",
        make: "TOYOTA",
        yearmodel: 2015,
        color: "Platinum White Pearl",
        officialreceiptnumber: "7513415",
        ORnumberdateissued: "2024-02-02",
        ORnumberexpirydate: "2025-02-02",
        authorizeperson1: "Esther Marin",
        authorizeperson2: "Teresa Mendez",
        authorizeperson3: "Jose Antonio Soto",
        authorizeperson4: "Maria Mar Ruiz",
        authorizeperson5: "Oscar Pierto",
        authorizeperson6: "",
        authorizeperson7: "",
        authorizeperson8: "",
        authorizeperson9: "",
        authorizeperson10: "",
    },
    {
        pid: 2,
        fullname: "tabe",
        idnumber: "20-21522",
        applicant: "Employee",
        position: "project manager",
        courseandyear: "",
        address: "dopaj, dupax del sur, nueva vizcaya",
        mobilenumber: "09677160884",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "2-Wheeled",
        platenumber: "DA 93600",
        make: "yamaha",
        yearmodel: 2018,
        color: "Matte Grey",
        officialreceiptnumber: "6442808",
        ORnumberdateissued: "2023-10-24",
        ORnumberexpirydate: "2024-10-24",
        authorizeperson1: "Gloria Peña",
        authorizeperson2: "Maria Rosario Soler",
        authorizeperson3: "Pablo Ferrer",
        authorizeperson4: "",
        authorizeperson5: "",
        authorizeperson6: "",
        authorizeperson7: "",
        authorizeperson8: "",
        authorizeperson9: "",
        authorizeperson10: "",
    },
    {
        pid: 4,
        fullname: "cJosep Ortega",
        idnumber: "20-21115",
        applicant: "Concessionaire",
        position: "vendor",
        courseandyear: "",
        address: "Raynor Greens, Macalelon Bataan",
        mobilenumber: "090038574",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "9169384",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    },
    {
        pid: 5,
        fullname: "Eduardo Moreno",
        idnumber: "20-21115",
        applicant: "Employee",
        position: "Security Guard",
        courseandyear: "",
        address: "Schulist Plaza Suite, Santa Rosa Mountain Province",
        mobilenumber: "040446402",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "9169384",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    },
    {
        pid: 6,
        fullname: "Emilio Dominguez",
        idnumber: "20-21115",
        applicant: "Employee",
        position: "Cashier",
        courseandyear: "",
        address: "Lockman Shore, Poblacion, Cebu City Cebu",
        mobilenumber: "023794962",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "9169384",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    },
    {
        pid: 7,
        fullname: "María Luisa Jimenez",
        idnumber: "20-21115",
        applicant: "Concessionaire",
        position: "vendor",
        courseandyear: "",
        address: "Von Hollow, Santa Rita Southern Leyte",
        mobilenumber: "682260017",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "9169384",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    },
    {
        pid: 8,
        fullname: "Susana Gallego",
        idnumber: "20-21115",
        applicant: "Student",
        position: "",
        courseandyear: "BS-ME 4",
        address: "Kuphal Hills, San Guillermo Camarines Norte ",
        mobilenumber: "599972314",
        driverslicense: "26567421258",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "9169384",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    },
    {
        pid: 9,
        fullname: "Mariano Gil",
        idnumber: "20-21115",
        applicant: "Student",
        position: "",
        courseandyear: "BS-HM 3",
        address: "Breitenberg Wells, Poblacion, Samal Surigao del Norte",
        mobilenumber: "714824036",
        driverslicense: "2414418445",
        dateissued: "09/24/2024",
        expiry: "2029-09-24",
        vehiclewheels: "3-Wheeled",
        platenumber: "AGA 1625",
        make: "Honda",
        yearmodel: 2014,
        color: "Black",
        officialreceiptnumber: "579691543",
        ORnumberdateissued: "2023-09-11",
        ORnumberexpirydate: "2024-09-11",
        authorizeperson1: "Francisco Ortiz",
        authorizeperson2: "Rosa María Ramos",
        authorizeperson3: "Fernando Crespo",
        authorizeperson4: "Cristina Parra",
        authorizeperson5: "Sergio Diez",
        authorizeperson6: "Ignacio Garrido",
        authorizeperson7: "María Fuentes",
        authorizeperson8: "Juan Carlos Lorenzo",
        authorizeperson9: "María Peña",
        authorizeperson10: "",
    }
]